### ISSUE TITLE
Provide type shortcuts for FutureBus<T>

### ISSUE THREAD

**Issue by peku33** [cere42/future-bus#3]
Hi,

At the moment if we want to store result of `future_bus::unbounded()` in a structure, knowing type `T`, we have to write `future_bus: FutureBus<T, futures::channel::mpsc::UnboundedSender<T>, futures::channel::mpsc::UnboundedReceiver<T>>` which is not very convinient.

Are there any plans to provide type aliases for those fields?

**Comment by stkfd** [comment]
Currently I use aliases in the projects where I use this library, but this seems like a good idea.

I could add aliases like `UnboundedFutureBus<T>` and `UnboundedBusSubscriber<T>` (+ same for the bounded variant). I don't think I could make it any shorter for cases with other non-default channel implementations, but that's a different issue.

**Comment by peku33** [comment]
Submitted here: https://github.com/cere42/future-bus/pull/4

**Comment by stkfd** [comment]
Looks good, merging it now. I'll create a point release on crates.io soon that will include it.
